### ISSUE TITLE
Runtime error when `bool` type value is passed to `NotifyField.notify.fields.value` 

### ISSUE THREAD

**Issue by Rindrics** [m-mizutani/ghnotify#11]
## What occurs

`: fail to unmarshal OPA server result to out: json: cannot unmarshal bool into Go struct field NotifyField.notify.fields.value of type string`

## It occurs when

POSTing JSON body below while testing https://github.com/m-mizutani/ghnotify/blob/main/examples/policy/new_deploy_key.rego :
```
{
    "action": "created",
    "key": {
        "title": "key-title",
        "read_only": true
    }
}
```

## What to expect

ghnotify should accept `bool` type value value for `NotifyField.notify.fields.value` because The field `key.read_only` of `deploy_key` event  is defined as `bool` (c.f. https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#deploy_key )

I will resolved this by #10

**Comment by m-mizutani** [comment]
@Rindrics 
I totally agree accepting boolean value in NotofyField.notify.fields.value. However it should not only boolean and string but also number, struct ,etc. So I created another PR https://github.com/m-mizutani/ghnotify/pull/12 to accept any type as NotifyField.Value.

Please let me know if you have something bad yet.
