### ISSUE TITLE
Endpoint for health checking?

### ISSUE THREAD

**Issue by Rindrics** [m-mizutani/ghnotify#5]
- what I need: an endpoint for health checking of ghnotify
- why I need it:
    - I need to specify health-checking endpoint when I deploy ghnotify to container hosting services (e.g. ECS on AWS)
    - As a workaround, I've been using `GET /` request and `404 Not found` response for health checking
- expectation:
    - I expect the new health-checking endpoint to return `2XX` response

**Comment by m-mizutani** [comment]
That makes sense and endpoint `/health` looks good for me. Let me review and merge #4 after resolving #3

**Comment by m-mizutani** [comment]
#4 has been merged and let me close the issue
